server:
  port: 8081

spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bmarket-trade-local
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
    database: mysql
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG
---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: "test"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bmarket-trade-test
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
    database: mysql
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG
---
server:
  port: 8081

spring:
  config:
    activate:
      on-profile: "production"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bmarket-trade-production
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: false # log
        show_sql: false
    open-in-view: false
    database: mysql
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: ERROR




