server:
  port: 8080

custom-key:
  secret-key: MySecreteKeyIsMySecreteKeyItIsMustBeGreaterThen512bits
  token-validation-life: 1800
  refresh-token-validation-life: 604800

spring:
  config:
    activate:
      on-profile: local


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bori-market-account
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG

internal:
  trade: http://localhost:8081
  address: http://localhost:8085
  frm:   http://localhost:8095
