server:
  port: 8080

custom-key:
  secret-key: MySecreteKeyIsMySecreteKeyItIsMustBeGreaterThen512bits
  token-validation-life: 10
  refresh-token-validation-life: 15

spring:
  application:
    name: security-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG
  h2:
    console:
      enabled: true
      path: /h2/console

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

internal:
  trade: http://localhost:8081/internal/trade
  address: http://localhost:8085/internal/address
  frm-profile: http://localhost:8095/internal/frm/profile
---
server:
  port: 0

custom-key:
  secret-key: MySecreteKeyIsMySecreteKeyItIsMustBeGreaterThen512bits
  token-validation-life: 600
  refresh-token-validation-life: 1800

spring:
  application:
    name: security-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bori-market-account-test
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

internal:
  trade: http://localhost:8081/internal/trade
  address: http://localhost:8085/internal/address
  frm-profile: http://localhost:8095/internal/frm/profile
---
server:
  port: 8080

custom-key:
  secret-key: MySecreteKeyIsMySecreteKeyItIsMustBeGreaterThen512bits
  token-validation-life: 600
  refresh-token-validation-life: 1800

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://is-secret/account?characterEncoding=UTF-8
    username: root
    password: 0209

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # log
        show_sql: true
    open-in-view: false
  logging:
    level:
      org.hibernate.SQL:
        type.descriptor.sql: trace
        SQL: DEBUG


internal:
  trade: http://is-secret/internal/trade
  address: http://is-secret/internal/address
  frm-profile:  http://is-secret/internal/frm/profile
